name: Terraform Destroy

on:
  workflow_dispatch: # Trigger manually from the Actions tab

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.2 

      - name: Set D_O S3Var
        run: |
         echo "AWS_ACCESS_KEY_ID=${{ secrets.DO_SPACES_ACCESS_KEY }}" >> $GITHUB_ENV
         echo "AWS_SECRET_ACCESS_KEY=${{ secrets.DO_SPACES_SECRET_KEY }}" >> $GITHUB_ENV
   
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_TOKEN }} 
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}

      - name: Terraform Destroy
        id: DESTROY
        run: terraform destroy -auto-approve -var "do_token=${{ secrets.DO_TOKEN }}" -var "public_key=${{ secrets.DO_SSH_PUBLIC_KEY }}"
        working-directory: ./terraform
        env:
          DO_TOKEN: ${{ secrets.DO_TOKEN }}